
GET http://localhost:3000/api/users
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "kyle",
    "password": "password"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "kyle",
    "password": "pasrd"
}
###
GET http://localhost:3000/greeting
